config/routes.rb
Rails.application.routes.draw do
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    get "signout" => "devise/sessions#destroy"
  end
  devise_for :users
  resources :line_items
  resources :giohangs
  get 'tiem/index'
  resources :sanphams
  root :to => 'tiem#index'
  get 'sanpham/chitiet', to: 'sanphams#show', as: "detail"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/giohang.rb
class Giohang < ApplicationRecord
    has_many :line_items, :dependent => :destroy

    def them_sanpham(sanpham_id)
        current_item = line_items.find_by_sanpham_id(sanpham_id)
        if current_item 
            current_item.quantity += 1
        else
            current_item = line_items.build(:sanpham_id => sanpham_id)
        end
        current_item
    end

    def total_price 
        line_items.to_a.sum { |item| item.total_price }
    end
end

app/controllers/giohangs_controller.rb
class GiohangsController < ApplicationController
  before_action :set_giohang, only: [:show, :edit, :update, :destroy]

  # GET /giohangs
  # GET /giohangs.json
  def index
    @giohangs = Giohang.all
  end

  # GET /giohangs/1
  # GET /giohangs/1.json
  def show
  end

  # GET /giohangs/new
  def new
    @giohang = Giohang.new
  end

  # GET /giohangs/1/edit
  def edit
  end

  # POST /giohangs
  # POST /giohangs.json
  def create
    @giohang = Giohang.new(giohang_params)

    respond_to do |format|
      if @giohang.save
        format.html { redirect_to @giohang, notice: 'Giohang was successfully created.' }
        format.json { render :show, status: :created, location: @giohang }
      else
        format.html { render :new }
        format.json { render json: @giohang.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /giohangs/1
  # PATCH/PUT /giohangs/1.json
  def update
    respond_to do |format|
      if @giohang.update(giohang_params)
        format.html { redirect_to @giohang, notice: 'Giohang was successfully updated.' }
        format.json { render :show, status: :ok, location: @giohang }
      else
        format.html { render :edit }
        format.json { render json: @giohang.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /giohangs/1
  # DELETE /giohangs/1.json
  def destroy
    @giohang = current_giohang
    @giohang.destroy
    session[:giohang_id] = nil

    respond_to do |format|
      format.html { redirect_to giohangs_url, notice: 'Đã hủy giỏ hàng' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_giohang
      @giohang = Giohang.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def giohang_params
      params.fetch(:giohang, {})
    end
end

app/helpers/giohangs_helper.rb
module GiohangsHelper
end

app/views/giohangs/_form.html.erb
<%= form_with(model: giohang, local: true) do |form| %>
  <% if giohang.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(giohang.errors.count, "error") %> prohibited this giohang from being saved:</h2>

      <ul>
      <% giohang.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/giohangs/edit.html.erb
<h1>Editing Giohang</h1>

<%= render 'form', giohang: @giohang %>

<%= link_to 'Show', @giohang %> |
<%= link_to 'Back', giohangs_path %>

app/views/giohangs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mục lục giỏ hàng</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @giohangs.each do |giohang| %>
      <tr>
        <td><%= link_to 'Xem', giohang %></td>
        <td><%= link_to 'Sửa', edit_giohang_path(giohang) %></td>
        <td><%= link_to 'Hủy', giohang, method: :delete, data: { confirm: 'Bạn chắc chứ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Giỏ hàng mới', new_giohang_path %>

app/views/giohangs/new.html.erb
<h1>New Giohang</h1>

<%= render 'form', giohang: @giohang %>

<%= link_to 'Back', giohangs_path %>

app/views/giohangs/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Giỏ hàng của bạn</h2>

<table>
    <% @giohang.line_items.each do |item| %>
        <tr>
            <td><%= item.quantity %> x </td>
            <td><%= item.sanpham.tieude %></td>
            <td class="item_price"><%= number_to_currency(item.total_price, precision: 0, :unit => "vnđ", delimiter: ',', format: "%n%u") %></td>
        </tr>
    <% end %>
     
    <tr class="total_line">
        <td colspan="2">Tổng</td>
        <td class="total_cell"><%= number_to_currency(@giohang.total_price, precision: 0, :unit => "vnđ", delimiter: ',', format: "%n%u") %></td>
    </tr>
</table>

<%= button_to 'Xóa giỏ hàng', 
    @cart, 
    :method => :delete,
    data: {:confirm => 'Bạn chắc chứ?'} %>

<%= link_to 'Sửa', edit_giohang_path(@giohang) %> |
<%= link_to 'Quay lại', giohangs_path %>