config/routes.rb
Rails.application.routes.draw do
  as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    get "signout" => "devise/sessions#destroy"
  end
  devise_for :users
  resources :line_items
  resources :giohangs
  get 'tiem/index'
  resources :sanphams
  root :to => 'tiem#index'
  get 'sanpham/chitiet', to: 'sanphams#show', as: "detail"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sanpham.rb
class Sanpham < ApplicationRecord
    has_many :line_items
    before_destroy :check_if_has_line_item
  
private
  
    def check_if_has_line_item
        if line_items.empty?
            return true
        else
            errors.add(:base, 'Sản phẩm này có một đơn hàng')
            return false
        end
    end
end

app/controllers/sanphams_controller.rb
class SanphamsController < ApplicationController
  before_action :set_sanpham, only: [:show, :edit, :update, :destroy]

  # GET /sanphams
  # GET /sanphams.json
  def index
    @sanphams = Sanpham.all
  end

  # GET /sanphams/1
  # GET /sanphams/1.json
  def show
    @sach = Sanpham.where("id = '"+params[:id]+"'")
  end

  # GET /sanphams/new
  def new
    @sanpham = Sanpham.new
  end

  # GET /sanphams/1/edit
  def edit
  end

  # POST /sanphams
  # POST /sanphams.json
  def create
    @sanpham = Sanpham.new(sanpham_params)

    respond_to do |format|
      if @sanpham.save
        format.html { redirect_to @sanpham, notice: 'Sanpham was successfully created.' }
        format.json { render :show, status: :created, location: @sanpham }
      else
        format.html { render :new }
        format.json { render json: @sanpham.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sanphams/1
  # PATCH/PUT /sanphams/1.json
  def update
    respond_to do |format|
      if @sanpham.update(sanpham_params)
        format.html { redirect_to @sanpham, notice: 'Sanpham was successfully updated.' }
        format.json { render :show, status: :ok, location: @sanpham }
      else
        format.html { render :edit }
        format.json { render json: @sanpham.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sanphams/1
  # DELETE /sanphams/1.json
  def destroy
    @sanpham.destroy
    respond_to do |format|
      format.html { redirect_to sanphams_url, notice: 'Sanpham was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sanpham
      @sanpham = Sanpham.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sanpham_params
      params.require(:sanpham).permit(:tieude, :noidung, :anh, :gia)
    end
end

app/helpers/sanphams_helper.rb
module SanphamsHelper
end

app/views/sanphams/_form.html.erb
<%= form_with(model: sanpham, local: true) do |form| %>
  <% if sanpham.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sanpham.errors.count, "error") %> prohibited this sanpham from being saved:</h2>

      <ul>
      <% sanpham.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tieude %>
    <%= form.text_field :tieude %>
  </div>

  <div class="field">
    <%= form.label :noidung %>
    <%= form.text_area :noidung, :rows => 6 %>
  </div>

  <div class="field">
    <%= form.label :anh %>
    <%= form.text_field :anh %>
  </div>

  <div class="field">
    <%= form.label :gia %>
    <%= form.text_field :gia %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sanphams/edit.html.erb
<h1>Editing Sanpham</h1>

<%= render 'form', sanpham: @sanpham %>

<%= link_to 'Show', @sanpham %> |
<%= link_to 'Back', sanphams_path %>

app/views/sanphams/index.html.erb
<div id="sanpham_list">
    <h1>Sản Phẩm</h1>
  
    <table>
    <% @sanphams.each do |sanpham| %>
        <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
  
            <td>
                <%= image_tag(sanpham.anh, :class => 'list_image') %>
                <div class="price_line">
                      <span class="price"><%= number_to_currency(sanpham.gia, precision: 0, :unit => "vnđ", delimiter: ',', format: "%n%u") %></span>
            </td>
  
            <td class="list_description">
                <dl>
                    <dt><%= sanpham.tieude%></dt>
                    <dd><%= truncate(strip_tags(sanpham.noidung),
                            :length => 10000) %></dd>
                </dl>
            </td>
  
            <td class="list_actions">
                <%= link_to 'Xem', sanpham %><br/>
                <%= link_to 'Sửa', edit_sanpham_path(sanpham) %><br/>
                <%= link_to 'Hủy', sanpham, 
                    data: { confirm: 'Bạn chắc chứ?' },
                    :method => :delete %>
            </td>
        </tr>
    <% end %>
    </table>
</div>

<br>

<%= link_to 'Sản Phẩm Mới', new_sanpham_path %>

app/views/sanphams/new.html.erb
<h1>New Sanpham</h1>

<%= render 'form', sanpham: @sanpham %>

<%= link_to 'Back', sanphams_path %>

app/views/sanphams/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag(@sanpham.anh, height:'400', width: '200') %>
<p>
  <strong>Tiêu đề</strong>
  <%= @sanpham.tieude %>
</p>

<p>
  <strong>Nội dung</strong>
  <%= @sanpham.noidung %>
</p>



<p>
  <strong>Giá</strong>
  <%= @sanpham.gia %>
</p>

<%# <%= link_to 'Edit', edit_sanpham_path(@sanpham) %> 
<%= link_to 'Back', sanphams_path %>